meta_product_name: "Hafuru"
meta_title: "Hafuru - Express Gratitude, Be Happy. Match on this amazing frequency"
meta_description: "A platform inviting users to share things they're grateful for, enable them to match and connect with people sharing the same #gratitude."
meta_image: "cover-hafuru.png"
twitter_account: "@hafuru2"
